url changed to mirrors.ustc.edu.cn #1471
ScoopInstaller/Main pull request #1476
Opened 2020-10-05 20:48 UTC by wstein

SF does not have all files available (at least the manifest file is missing).
So I choose mirrors.ustc.edu.cn, which seems to be a good performing mirror.

Closes #1471

2020-10-06 10:10 UTC, janymal commented
I think that changing the mirror to SourceForge would perform better as it's not subordinated to one specific location. SourceForge basically has its own mirror network for even serving files across the globe so it would be more universal solution than fixing the mirror to China.

2020-10-08 10:02 UTC, thfr requested changes
Seems like there is a gcc-9.3.0-2 available now.

2020-10-08 10:02 UTC, thfr commented on bucket/gcc.json
> +                "http://mirrors.ustc.edu.cn/msys2/mingw/x86_64/mingw-w64-x86_64-libtasn1-4.9-1-any.pkg.tar.xz",
This file is not available any more, it is now `mingw-w64-x86_64-libtasn1-4.15.0-1-any.pkg.tar.xz`

2020-10-08 21:13 UTC, wstein commented
http://repo.msys2.org/mingw/x86_64/ is up again, so there is no need to fix the url.

2020-10-08 21:13 UTC, closed without merging