pyenv: Add version 2.64.3
ScoopInstaller/Main pull request #1559
Opened 2020-11-06 17:09 UTC by Vixb1122

2020-11-08 16:16 UTC, rasa requested changes
@Vixb1122: This is a 64-bit version, correct? If so, we should wrap the url/hash in an `architecture` tag. See
https://github.com/ScoopInstaller/Main/blob/fc3b9293828f1a7196ae4d8336f5df7eb522d084/bucket/wrangler.json#L6-L11
and
https://github.com/ScoopInstaller/Main/blob/fc3b9293828f1a7196ae4d8336f5df7eb522d084/bucket/wrangler.json#L17-L24
for examples.

2020-11-09 01:53 UTC, Vixb1122 commented
@rasa review again pls

2020-11-20 18:08 UTC, Vixb1122 commented
Please review again. @rasa

2020-12-10 07:04 UTC, rasa approved these changes

2020-12-18 21:59 UTC, merged