Create xray.json
ScoopInstaller/Main pull request #1614
Opened 2020-11-26 01:54 UTC by lifansama

Xray, Penetrates Everything. Also the best v2ray-core, with XTLS support. Fully compatible configuration.

2020-11-26 22:00 UTC, rasa requested changes

2020-11-26 22:00 UTC, rasa commented on bucket/xray.json
> +	}
```suggestion
	},
	"autoupdate": {
		"64bit": {
			"url": "https://github.com/XTLS/Xray-core/releases/download/v$version/Xray-windows-64.zip"
		},
		"32bit": {
			"url": "https://github.com/XTLS/Xray-core/releases/download/v$version/Xray-windows-32.zip"
		}
	}
```

2020-12-03 09:57 UTC, kidonng approved these changes

2020-12-03 09:57 UTC, kidonng commented on bucket/xray.json
> +	"license": "MPL",
```suggestion
	"license": "MPL-2.0",
```

2020-12-03 09:57 UTC, kidonng commented on bucket/xray.json
> +	"description": "Xray, Penetrates Everything. Also the best v2ray-core, with XTLS support. Fully compatible configuration.",
Don't use the advertising words from the project itself. You may check out [an example](https://github.com/kidonng/sushi/blob/21e8c412c234324267ccdfc7f008296882a69387/bucket/xray.json#L3) of an appropriate description.

2020-12-03 09:57 UTC, kidonng commented on bucket/xray.json
> +		"xray.exe"
Remove the array.

2020-12-03 09:57 UTC, kidonng commented on bucket/xray.json
> +		"github": "https://github.com/XTLS/Xray-core"
Just use `"checkver": "github"`

2021-02-01 01:24 UTC, earnestma requested changes

2021-02-01 01:24 UTC, earnestma commented on bucket/xray.json
> +}
tabs -> spaces

```suggestion
{
    "version": "1.0.0",
    "description": "Xray, Penetrates Everything. Also the best v2ray-core, with XTLS support. Fully compatible configuration.",
    "homepage": "https://github.com/XTLS/Xray-core",
    "license": "MPL-2.0",
    "architecture": {
        "64bit": {
            "url": "https://github.com/XTLS/Xray-core/releases/download/v1.0.0/Xray-windows-64.zip",
            "hash": "9B525F9945AAC08A0752055CFD3EFA7779A8D86DC2D4BC1EDFA49B6300593CD1"
        },
        "32bit": {
            "url": "https://github.com/XTLS/Xray-core/releases/download/v1.0.0/Xray-windows-32.zip",
            "hash": "18E099E12B9DCEAAE546D840C2BEEE00A3BB2D47EB390B347CF33E3372E2F9B6"
        }
    },
    "bin": [
        "xray.exe"
    ],
    "checkver": {
        "github": "https://github.com/XTLS/Xray-core"
    }
}
```

2021-02-01 01:36 UTC, earnestma requested changes

2021-02-01 01:36 UTC, earnestma commented on bucket/xray.json
> +	"description": "Xray, Penetrates Everything. Also the best v2ray-core, with XTLS support. Fully compatible configuration.",
Description

```suggestion
{
    "version": "1.0.0",
    "description": "Network tools for the XTLS protocol",
```

2021-02-01 01:36 UTC, earnestma commented on bucket/xray.json
> +	},
tabs -> spaces

```suggestion
    "homepage": "https://github.com/XTLS/Xray-core",
    "license": "MPL-2.0",
    "architecture": {
        "64bit": {
            "url": "https://github.com/XTLS/Xray-core/releases/download/v1.0.0/Xray-windows-64.zip",
            "hash": "9B525F9945AAC08A0752055CFD3EFA7779A8D86DC2D4BC1EDFA49B6300593CD1"
        },
        "32bit": {
            "url": "https://github.com/XTLS/Xray-core/releases/download/v1.0.0/Xray-windows-32.zip",
            "hash": "18E099E12B9DCEAAE546D840C2BEEE00A3BB2D47EB390B347CF33E3372E2F9B6"
        }
    },
```

2021-02-01 01:36 UTC, earnestma commented on bucket/xray.json
> +	],
```suggestion
    "bin": "xray.exe",
```

2021-02-01 01:36 UTC, earnestma commented on bucket/xray.json
> +	}
```suggestion
    "checkver": "github",
```

2021-04-02 09:09 UTC, closed without merging