starship: add 32bit version
ScoopInstaller/Main pull request #1790
Opened 2021-01-30 11:51 UTC by davidkna

starship v0.49.0 added a 32bit build for windows.

2021-01-30 16:53 UTC, earnestma requested changes
Make sure to also give autoupdate URL to 32-bit:

```
diff --git a/bucket/starship.json b/bucket/starship.json
index 9f57f9772..8fbe574ce 100644
--- a/bucket/starship.json
+++ b/bucket/starship.json
@@ -28,6 +28,9 @@
         "architecture": {
             "64bit": {
                 "url": "https://github.com/starship/starship/releases/download/v$version/starship-x86_64-pc-windows-msvc.zip"
+            },
+            "32bit": {
+                "url": "https://github.com/starship/starship/releases/download/v$version/starship-i686-pc-windows-msvc.zip"
             }
         },
         "hash": {
```

2021-01-31 13:44 UTC, earnestma commented
/verify

2021-01-31 13:57 UTC, earnestma submitted a review, later dismissed

2021-02-07 08:05 UTC, chawyehsu approved these changes

2021-02-07 08:05 UTC, merged