ht-rs: Add version 0.4.0
ScoopInstaller/Main pull request #1800
Opened 2021-02-06 16:55 UTC by myty

Adds a manifest for https://github.com/ducaale/ht

2021-02-06 16:55 UTC, myty commented
/verify

2021-02-07 14:16 UTC, ducaale commented
@myty ht author here, Would you mind renaming `ht-rs` to be consistent with the [homebrew-core](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ht-rust.rb) version which is now called ht-rust? Thank you very much!

2021-02-07 14:21 UTC, myty commented
> @myty ht author here, would you mind renaming `ht-rs` to be consistent with the [homebrew-core](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ht-rust.rb) version which is now called ht-rust? Thank you very much!

For sure!

2021-02-07 15:09 UTC, myty commented
/verify

2021-02-07 15:32 UTC, myty commented
> [Your changes do not pass checks.](https://github.com/Ash258/Scoop-GithubActions/wiki/Pull-Request-Checks)
> 
> ### ht-rust
> * [x]  Description
> * [x]  License
> * [x]  Hashes
> * [ ]  Checkver
> * [x]  Autoupdate

Not sure why Checkver is failing.  I'm going to run verify again. 🤷🏻‍♂️

2021-02-07 15:33 UTC, myty commented
/verify

2021-02-07 15:40 UTC, myty commented
/verify

2021-02-07 17:21 UTC, earnestma requested changes

2021-02-07 17:21 UTC, earnestma commented on bucket/ht-rust.json
> +    "version": "0.5.0",
Formatting

```suggestion
    "version": "0.5.0",
    "description": "Yet another HTTPie clone in Rust",
    "homepage": "https://github.com/ducaale/ht",
    "license": "MIT",
```

2021-02-07 17:21 UTC, earnestma commented on bucket/ht-rust.json
> +    "hash": "eca94991b75ac4cb718f6c1449ae521ea692c73ab5ee1ff326e28636f3314c1a",
afaik x64_64 means 64-bit only:

```suggestion
    "architecture": {
        "64bit": {
            "url": "https://github.com/ducaale/ht/releases/download/v0.5.0/ht-x86_64-pc-windows-msvc.zip",
            "hash": "eca94991b75ac4cb718f6c1449ae521ea692c73ab5ee1ff326e28636f3314c1a"
        }
    },
```

2021-02-07 17:21 UTC, earnestma commented on bucket/ht-rust.json
> +    },
When homepage is same as Github repo link, there is no need to specify twice

```suggestion
    "checkver": "github",
```

2021-02-07 17:21 UTC, earnestma commented on bucket/ht-rust.json
> +}
Autoupdate:

```suggestion
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/ducaale/ht/releases/download/v$version/ht-x86_64-pc-windows-msvc.zip"
            }
        }
    }
}
```

2021-02-07 17:45 UTC, myty commented
/verify

2021-02-12 19:55 UTC, ducaale commented
v0.7.0 of `ht` has been renamed to `xh` due to name collision with `/usr/bin/ht` from TextLive. See https://github.com/ducaale/xh/issues/1

2021-02-14 20:12 UTC, myty commented
/verify

2021-02-14 20:29 UTC, r15ch13 approved these changes

2021-02-14 20:29 UTC, merged