Add dapr
ScoopInstaller/Main pull request #1839
Opened 2021-02-20 06:45 UTC by JadynWong

2021-02-23 00:20 UTC, JadynWong commented
/verify

2021-03-01 20:46 UTC, earnestma requested changes
Just minor nitpicks

2021-03-01 20:46 UTC, earnestma commented on bucket/dapr-cli.json
> +    "description": "The Dapr CLI allows you to setup Dapr on your local dev machine or on a Kubernetes cluster, provides debugging support, launches and manages Dapr instances.",
```suggestion
    "description": "Command-line tools for Dapr",
```

2021-03-01 20:46 UTC, earnestma commented on bucket/dapr-cli.json
> +    "homepage": "https://github.com/dapr/cli/",
```suggestion
    "homepage": "https://github.com/dapr/cli",
```

2021-03-02 01:14 UTC, JadynWong commented
> Just minor nitpicks

Thanks for the suggestion, already applied.

2021-03-22 15:51 UTC, JadynWong commented
Hi @earnestma,
Can you help me to get this PR approved? 
Thank you very much!

2021-03-22 18:33 UTC, earnestma commented
Would you mind updating the manifest to v1.0.1? https://github.com/dapr/cli/releases/tag/v1.0.1

2021-03-22 19:03 UTC, JadynWong commented
> Would you mind updating the manifest to v1.0.1? https://github.com/dapr/cli/releases/tag/v1.0.1

Thanks.
It has been updated to v1.0.1.

2021-03-23 15:37 UTC, JadynWong commented
/verify

2021-04-02 09:47 UTC, chawyehsu approved these changes

2021-04-02 09:47 UTC, merged