powerline-go: Add version 1.21.0
ScoopInstaller/Main pull request #1970
Opened 2021-03-22 16:00 UTC by i-ghost

2021-03-24 17:26 UTC, CryoRenegade requested changes
Add a newline at the end of the file.

2021-03-26 00:23 UTC, CryoRenegade commented
/verify

2021-04-10 11:13 UTC, pratikpc commented
@i-ghost can you add check-ver to support auto-updation?

2021-05-12 14:38 UTC, i-ghost commented
@pratikpc That's done now, sorry for the delay.

2021-10-29 23:51 UTC, i-ghost commented
@rashil2000 Changes implemented, rebased on latest upstream `master`, and squashed commits.

2021-10-30 03:50 UTC, rashil2000 commented
/verify

2021-10-30 03:52 UTC, pratikpc requested changes

2021-10-30 03:52 UTC, pratikpc commented on bucket/powerline-go.json
> +        "url": "https://github.com/justjanne/powerline-go/releases/download/v$version/powerline-go-windows-amd64#/powerline-go.exe"
Needs architecture and 64bit

2021-10-30 03:52 UTC, pratikpc commented
Are the GitHub Actions broken?

2021-10-30 06:23 UTC, pratikpc approved these changes

2021-10-30 06:28 UTC, merged