gdu@5.1.0: Add manifest
ScoopInstaller/Main pull request #2311
Opened 2021-06-21 07:27 UTC by rashil2000

Disk usage analyzer with console interface written in Go

Ref: https://github.com/dodorz/scoop/blob/master/gdu.json

2021-06-21 07:27 UTC, rashil2000 commented
/verify

2021-08-13 11:24 UTC, telenieko commented
Note that a PR for gdu is already open on lukesampson/scoop-extras#6098

2021-08-13 12:07 UTC, rashil2000 commented
How exactly does one measure 'popularity'? If we go by GitHub stars, gdu is more popular than a similar tool called [dua](https://github.com/Byron/dua-cli) (which is already in main bucket), and is just a year younger. 

I don't think popularity/age is the problem. This repository is effectively defunct, just look at the amount of trivial open PRs.

2021-08-13 12:11 UTC, telenieko commented
There is no clear guidelines as far as I know.

I tend to check stars, stack overflow, or Google search results.

In any case I personally default to Extras

2021-08-13 12:15 UTC, rashil2000 commented
Yeah, at least that one seems to be regularly maintained, for now.

2021-09-10 07:31 UTC, rashil2000 commented
Sorry I don't know how to put hash in the autoupdate field, could you point me towards an example?

2021-09-10 08:25 UTC, stevehipwell requested changes
Please see suggestions for the updated version, how to use a different shim name and how to use hashes.

2021-09-10 08:25 UTC, stevehipwell commented on bucket/gdu.json
> +    "bin": "gdu.exe",
```suggestion
    "version": "5.7.0",
    "architecture": {
        "64bit": {
            "url": "https://github.com/dundee/gdu/releases/download/v5.7.0/gdu_windows_amd64.exe.zip",
            "hash": "e21f1798bc44c6d2e65fc3b9c7d43c46ebb66e7eeac97d113327acaf8893d973"
        }
    },
    "bin": [
        [
            "gdu_windows_amd64.exe",
            "gdu"
        ]
    ],
```

2021-09-10 08:25 UTC, stevehipwell commented on bucket/gdu.json
> +        }
```suggestion
        },
        "hash": {
            "url": "$baseurl/sha256sums.txt"
        }
```

2021-09-10 10:54 UTC, rashil2000 commented
@stevehipwell made the changes, let me know if they're fine

2021-09-10 10:56 UTC, stevehipwell approved these changes

2021-09-10 11:02 UTC, merged

2021-09-10 11:35 UTC, rashil2000 commented
@stevehipwell Just wanted to ask something. This repo was inactive for a long while (7-8 months), and it seems to have become active again. That said, I've had some CLI tools manifests with me for a while (all of them fit the Main bucket's criteria), I was holding myself from sending any PRs. Should I open a PR for each one of them (8-9 manifests), or a single PR would do?

2021-09-10 11:38 UTC, stevehipwell commented
There have been a couple of new maintainers added (see https://github.com/ScoopInstaller/Main/issues/2403). For me I'd strongly prefer a single PR for each tool to keep the commits consistent and tracable.

2021-09-10 11:48 UTC, rashil2000 commented
Ah, thanks for the heads up!

Will do as you say.