qr: Add version 1.0.0
ScoopInstaller/Main pull request #2998
Opened 2021-11-22 20:56 UTC by tpanj

New package of utility.

2021-11-23 01:00 UTC, tech189 requested changes
```
"extract_dir": "\\",
```
Do not need this line - scoop will automatically extract the root directory of the zip file. Otherwise installation fails.

Add the following so scoop can get updates from github releases:
```
"checkver": "github",
    "autoupdate": {
        "url": "https://github.com/tpanj/qr/releases/download/v1.0.0/qr-$version-windows.zip"
    }
```

2021-11-23 01:49 UTC, tpanj commented
> ```
> "extract_dir": "\\",
> ```
> Do not need this line - scoop will automatically extract the root directory of the zip file. Otherwise installation fails.
No, then this line is not needed.

> 
> Add the following so scoop can get updates from github releases:
> 
> ```
> "checkver": "github",
> "autoupdate": {
>     "url": "https://github.com/tpanj/qr/releases/download/v1.0.0/qr-$version-windows.zip"
> }
> ```
Thanks!

2021-11-23 05:25 UTC, niheaven commented
@tpanj As the author of qr, could you please release sha256 checksum?

2021-11-23 05:50 UTC, rashil2000 commented
@tpanj As far as I understand, this repo was started just yesterday, and hence doesn't qualify for the Main criteria. 

This is why I insist on opening a Package Request first in the instructions template, which you didn't.

2021-11-24 06:36 UTC, tpanj commented
> @tpanj As the author of qr, could you please release sha256 checksum?

You probably mean enclosed to qr...zip file?

2021-11-29 02:57 UTC, niheaven commented
No, I mean a separate .sha256 file that contains hash, so Scoop's autoupdate could read hash from it instead of downloading and doing a local hash.

2021-11-29 15:18 UTC, tpanj commented
> No, I mean a separate .sha256 file that contains hash, so Scoop's autoupdate could read hash from it instead of downloading and doing a local hash.

Like here [link](https://github.com/tpanj/qr/releases/download/v1.0.0/SHA256SUMS) ?

2021-11-29 18:30 UTC, niheaven commented
Yes, and you'd better renamed this file to `qr-1.0.0-windows.zip.sha256` and changed au section of manifest to:

```json
    "autoupdate": {
        "url": "https://github.com/tpanj/qr/releases/download/v$version/qr-$version-windows.zip",
		"hash": {
			"url": "$url.sha256"
		}
    }
```

2021-11-30 03:43 UTC, niheaven approved these changes

2021-11-30 03:46 UTC, niheaven commented on bucket/qr.json
> +
```suggestion
    }
```

2021-11-30 03:47 UTC, niheaven requested changes
Remove that blank line

2021-11-30 05:29 UTC, niheaven approved these changes

2021-11-30 05:29 UTC, merged