sttr: add version 0.2.12
ScoopInstaller/Main pull request #3123
Opened 2021-12-25 20:57 UTC by abhimanyu003

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2021-12-26 03:56 UTC, tech189 commented
Hi! Thanks for your PR, please could you follow the contribution guide and give some details about the popularity of this program? Next time it would be great if you could create an issue for discussion first :) At a glance it seems a popular program but I will take a closer look tomorrow. Could you also please fix the manifest so that it passes the checks?

2021-12-26 07:06 UTC, rashil2000 requested changes

2021-12-26 07:06 UTC, rashil2000 commented on bucket/sttr.json
> +    "description": "cross-platform, cli app to perform various operations on string",
```suggestion
    "description": "Command line application to perform various operations on strings",
```

2021-12-26 07:06 UTC, rashil2000 commented on bucket/sttr.json
> +    },
```suggestion
    "license": "MIT",
```

2021-12-26 07:06 UTC, rashil2000 commented on bucket/sttr.json
> +            "url": "$baseurl/checksums.txt"
```suggestion
            "url": "$baseurl/sttr_$version_checksums.txt"
```

2021-12-26 07:07 UTC, rashil2000 commented
https://github.com/ScoopInstaller/Main/pull/2859#issuecomment-955644109

2021-12-26 08:42 UTC, abhimanyu003 commented
Hello, @tech189 and @rashil2000 thanks so much for your feedback and suggestions.
It's command-line software so I thought it will be allowed. 
Few points: It's not on 500 starts yet, but it was trending #3 on ProductHunt https://www.producthunt.com/posts/sttr 
It's not downloading anything or opening up any ports or runs in the background, security is not an issue here.

I tried to fix the manifest as per review comments but somehow it keeps on failing. 

Please let me know your thoughts.

2021-12-26 12:23 UTC, rashil2000 commented
There's good reason why we **insist** on contributors opening issues first for any PR, so that such discussions can be had.

> It's command-line software so I thought it will be allowed.

It's not the only [criterion](https://github.com/ScoopInstaller/scoop/wiki/Criteria-for-including-apps-in-the-main-bucket).

> It's not downloading anything or opening up any ports or runs in the background, security is not an issue here.

We know, we can all see the source code there :)

The popularity/age criterion is present to establish a base level of trust. The release artifacts an author puts on their GitHub repo can be modified, even if they're released through an automated process (like GitHub Actions).

> I tried to fix the manifest as per review comments but somehow it keeps on failing.

Our CI is broken as of now, you can ignore it.

> Please let me know your thoughts.

If you insist, you can shift this PR to Extras bucket.

2021-12-27 09:28 UTC, abhimanyu003 commented
Sure I will look forward to adding it there. Currently closing this PR.

2021-12-27 09:28 UTC, closed without merging

2021-12-27 19:25 UTC, tech189 commented
If it doesn’t make it into the Extras bucket, it’s very easy to set up a bucket for your own apps. It would only be one extra cmd for your users to run.

2021-12-31 15:12 UTC, rashil2000 commented
> Sure I will look forward to adding it there.

Hey @abhimanyu003 :) 
Any updates?

2021-12-31 15:41 UTC, tech189 commented
I added it to my bucket in the meantime, just run the following:
```
scoop bucket add tech189 https://github.com/tech189/tech189-bucket
```
Then install with:
```
scoop install sttr
```

2021-12-31 15:48 UTC, rashil2000 commented
Interesting!

I'd like to add that we have made a template repository for making personal buckets very easily - https://github.com/ScoopInstaller/BucketTemplate - which has [several advantages](https://github.com/ScoopInstaller/Scoop/wiki/Buckets#using-template).

2022-01-01 12:54 UTC, tech189 commented
Oh, I didn't know about that template! I'm going to try migrating my bucket to it by copying what my bucket doesn't have.

2022-01-06 12:43 UTC, tech189 commented
@rashil2000 just to let you know, I've successfully migrated and set up CI tests in my bucket!

2022-01-06 13:06 UTC, rashil2000 commented
Nice! 😃