pdfbox: Add version 2.0.5
ScoopInstaller/Main pull request #3126
Opened 2021-12-27 23:07 UTC by sualeh

2021-12-27 23:36 UTC, tech189 approved these changes

2021-12-28 00:42 UTC, sualeh commented
@rashil2000  - are you able to merge this in? @tech189 has taken a look. Thanks.

2021-12-28 00:50 UTC, tech189 commented
Could you add autoupdate so that we don't need to manually update this manifest in future? You could base it on my suggestion https://github.com/ScoopInstaller/Versions/pull/358#pullrequestreview-840599804 where I added autoupdate.

2021-12-28 01:10 UTC, sualeh commented
/verify

2021-12-28 01:11 UTC, sualeh commented
@tech189  - thanks for your gentle tutorial. :-)

2021-12-28 01:11 UTC, tech189 approved these changes

2021-12-28 01:12 UTC, tech189 commented
No problem, it all looks good now!

2021-12-28 01:23 UTC, sualeh commented
@rashil2000 - this one is ready to go! Thanks for all your help, @tech189.

2021-12-28 05:44 UTC, rashil2000 requested changes

2021-12-28 05:44 UTC, rashil2000 commented on bucket/pdfbox.json
> +          "regex": "$sha512"
```suggestion
          "url": "$url.sha512"
```

2021-12-28 05:44 UTC, rashil2000 commented on bucket/pdfbox.json
> +          "regex": "$sha512"
```suggestion
          "url": "$url.sha512"
```

2021-12-28 06:38 UTC, niheaven commented
Only need one hash section

2021-12-28 06:39 UTC, rashil2000 commented
/verify

2021-12-28 06:41 UTC, merged