Add ghorg 1.7.6
ScoopInstaller/Main pull request #3192
Opened 2022-01-15 17:25 UTC by Slach

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-01-15 17:29 UTC, rashil2000 requested changes

2022-01-15 17:29 UTC, rashil2000 commented on bucket/ghorg.json
> +    },
```suggestion
    "checkver": "github",
```

2022-01-15 17:33 UTC, rashil2000 commented
/verify

2022-01-15 17:35 UTC, merged

2022-08-24 22:42 UTC, gabrie30 commented
Thanks for adding ghorg! I'll update the readme to make sure users know its available via scoop.