dbmate: Add version 1.12.1
ScoopInstaller/Main pull request #3204
Opened 2022-01-18 19:16 UTC by littleli

Dbmate is a lightweight standalone database migration tool, to keep your database schema in sync across multiple developers and your production servers.

Homepage: https://github.com/amacneil/dbmate

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-01-19 02:41 UTC, rashil2000 requested changes
Update to 1.13.0

2022-01-19 09:04 UTC, littleli commented
Oh, they did update meanwhile? Bummer.

2022-01-19 09:42 UTC, rashil2000 commented
/verify

2022-01-19 09:45 UTC, merged

2022-01-30 21:17 UTC, amacneil commented
Dbmate author here: I'm sorry, no `.exe` was an unintentional mistake in the release script (only noticed it after I read your comment). I'll fix that in the next version.

2022-01-31 04:57 UTC, rashil2000 commented
Thanks for the update @amacneil!

Pinging @littleli :)