gotify-cli: Add version 2.2.1 - gotify-server: Add version 2.1.4
ScoopInstaller/Main pull request #3250
Opened 2022-01-24 21:05 UTC by graphixillusion

Adding this two new app manifest:

gotify-cli: version 2.2.1
gotify-server: version 2.1.4

Relates to #1011

2022-01-24 21:06 UTC, graphixillusion commented
/verify

2022-01-25 10:45 UTC, rashil2000 requested changes

2022-01-25 10:45 UTC, rashil2000 commented on bucket/gotify-cli.json
> +}
```suggestion
}

```

2022-01-25 10:45 UTC, rashil2000 commented on bucket/gotify-server.json
> +}
```suggestion
}

```

2022-01-25 10:57 UTC, rashil2000 requested changes

2022-01-25 10:57 UTC, rashil2000 commented on bucket/gotify-cli.json
> +    "description": "A command line interface for pushing messages to gotify/server",
```suggestion
    "description": "A command line interface for pushing messages to Gotify server",

```

2022-01-25 10:57 UTC, rashil2000 commented on bucket/gotify-server.json
> +    "description": "A simple server for sending and receiving messages in real-time per WebSocket. (Includes a sleek web-ui)",
```suggestion
    "description": "A simple server for sending and receiving messages in real-time per WebSocket, with a sleek web UI",

```

2022-01-25 10:57 UTC, rashil2000 commented on bucket/gotify-server.json
> +    },
```suggestion
    "architecture": {
        "64bit": {
            "url": "https://github.com/gotify/server/releases/download/v2.1.4/gotify-windows-amd64.exe.zip",
            "hash": "adf8bdad8ec032325169b0dbaa5952bc13fb547b570532cef60f2007623fcc93"
        },
		"32bit": {
            "url": "https://github.com/gotify/server/releases/download/v2.1.4/gotify-windows-386.exe.zip",
            "hash": "d3073247f1d6164362dfb1d279e40d664e3209672e6993763853defb561bb88a"
        }
    },    
    "pre_install": "Rename-Item \"$dir\\gotify-windows-*\" gotify.exe",
    "bin": "gotify.exe",
```

We can simplify this a bit

2022-01-25 10:58 UTC, rashil2000 commented
This is your first contribution, right? Excellent manifests, btw! Just some minor comments.

2022-01-25 14:15 UTC, graphixillusion commented
> This is your first contribution, right? Excellent manifests, btw! Just some minor comments.

Yep! First one. Thank you! I should do something else?

2022-01-25 14:18 UTC, rashil2000 commented
> I should do something else?

Check the review comments above (5 in total).

2022-01-25 14:40 UTC, rashil2000 requested changes
Remove empty newlines

2022-01-25 14:40 UTC, rashil2000 commented on bucket/gotify-cli.json
> +
```suggestion
```

2022-01-25 14:40 UTC, rashil2000 commented on bucket/gotify-server.json
> +
```suggestion
```

2022-01-25 14:57 UTC, rashil2000 commented
/verify

2022-01-25 15:00 UTC, merged