pdfcpu: Add version 0.3.13
ScoopInstaller/Main pull request #3258
Opened 2022-01-26 16:43 UTC by febkor

Closes #3257

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-01-26 16:44 UTC, febkor commented
/verify

2022-01-26 17:53 UTC, rashil2000 requested changes

2022-01-26 17:53 UTC, rashil2000 commented on bucket/pdfcpu.json
> +    "description": "A PDF processor written in Go.",
```suggestion
    "description": "A PDF processor written in Go, supporting encryption.",
```

2022-01-26 17:53 UTC, rashil2000 commented on bucket/pdfcpu.json
> +    "homepage": "https://github.com/pdfcpu/pdfcpu",
```suggestion
    "homepage": "https://pdfcpu.io",
```

2022-01-26 17:53 UTC, rashil2000 commented on bucket/pdfcpu.json
> +    "checkver": "github",
```suggestion
    "checkver": {
        "github": "https://github.com/pdfcpu/pdfcpu"
    },
```

2022-01-26 17:54 UTC, rashil2000 commented
In autoupdate, hash logic is same for both architectures, so it can be moved out of architecture block

2022-01-26 23:15 UTC, tech189 approved these changes

2022-01-27 04:19 UTC, rashil2000 commented
/verify

2022-01-27 04:21 UTC, merged