go-swagger: Add version 0.29.0
ScoopInstaller/Main pull request #3265
Opened 2022-01-28 15:00 UTC by littleli

This utility brings to the go community a complete suite of fully-featured, high-performance, API components to work with a Swagger API: server, client and data model.

From the actual README this utility allows you to:

- Generates a server from a swagger specification
- Generates a client from a swagger specification
- Generates a CLI (command line tool) from a swagger specification (alpha stage)
- Supports most features offered by jsonschema and swagger, including polymorphism
- Generates a swagger specification from annotated go code
- Additional tools to work with a swagger spec
- Great customization features, with vendor extensions and customizable templates

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-01-28 17:27 UTC, rashil2000 commented
Rename to `go-swagger.json`. `swagger.json` is too generic.

2022-01-28 23:06 UTC, littleli commented
> Rename to `go-swagger.json`. `swagger.json` is too generic.

Ok. Should I rename the binary to `go-swagger.exe` also?

2022-01-30 09:19 UTC, rashil2000 commented
No no, the executable name is fine as-is - swagger.exe. Note that we tend to use the same name for the executable as is mentioned in their docs - https://goswagger.io/#use-cases

2022-01-30 13:45 UTC, littleli commented
> No no, the executable name is fine as-is - swagger.exe. Note that we tend to use the same name for the executable as is mentioned in their docs - https://goswagger.io/#use-cases

Done.

2022-01-31 04:59 UTC, rashil2000 commented
/verify

2022-01-31 05:01 UTC, rashil2000 requested changes

2022-01-31 05:01 UTC, rashil2000 commented on bucket/go-swagger.json
> +    "description": "Command-line tool to help working with swagger",
```suggestion
    "description": "Golang implementation of Swagger 2.0 (OpenAPI 2.0)",
```

2022-01-31 05:01 UTC, rashil2000 commented on bucket/go-swagger.json
> +    "license": "Unlicense",
```suggestion
    "license": "Apache-2.0",
```

2022-01-31 09:45 UTC, merged