sed: Rename binary before shimming
ScoopInstaller/Main pull request #3718
Opened 2022-06-28 15:09 UTC by sitiom

Same reason with https://github.com/ScoopInstaller/Main/pull/3717.

For sed, however, I'm not sure why it is showing the full path:
![image](https://user-images.githubusercontent.com/56180050/176214643-999ac7d6-b5b3-4145-87b5-dcad3f55e29c.png)

But I guess it's better than the latter.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2022-06-28 15:32 UTC, rasa requested changes

2022-06-28 15:32 UTC, rasa commented on bucket/sed.json
> +        "Move-Item \"$dir\\sed-4.8-x64.exe\" \"$dir\\x64\\sed.exe\"",
Please replace `4.8` with `$version` on both lines

2022-06-28 16:09 UTC, niheaven commented on bucket/sed.json
> +        "Move-Item \"$dir\\sed-$version-xp.exe\" \"$dir\\x86\\sed.exe\""
Use arch-specific scripts and remove unused one, don't mkdir for diff arch.

2022-06-29 02:58 UTC, niheaven approved these changes

2022-06-29 03:07 UTC, merged