mingw : update to version 12.2.0-rt_v10-rev2
ScoopInstaller/Main pull request #4508
Opened 2023-03-04 17:58 UTC by Baneeishaque

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-03-05 06:07 UTC, rashil2000 commented
Please use the `UCRT` variant. `MSVCRT` is the legacy one.

2023-03-08 05:42 UTC, niheaven requested changes

2023-03-08 05:42 UTC, niheaven commented on bucket/mingw.json
>          "url": "https://github.com/niXman/mingw-builds-binaries/releases",
```suggestion
        "github": "https://github.com/niXman/mingw-builds-binaries",
```

2023-03-08 05:42 UTC, niheaven commented on bucket/mingw.json
> +        "regex": "Release of ([\\d.]+)-(?<build>[a-z0-9_\\-]+)",
```suggestion
        "regex": "tag/([\\d.]+)-(?<build>[a-z0-9_\\-]+)",
```

2023-03-19 05:57 UTC, rashil2000 commented
/verify

2023-03-19 06:10 UTC, merged