selenium-manager : Add Version 1.0.0-M3
ScoopInstaller/Main pull request #4518
Opened 2023-03-06 13:40 UTC by Baneeishaque

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-03-08 19:56 UTC, rashil2000 requested changes
This is a 64bit application, so the architecture block is needed.

2023-03-08 19:56 UTC, rashil2000 commented on bucket/selenium-manager.json
> +    "description": "Selenium Manager is a CLI (Command-Line Interface) tool developed in Rust to allow cross platform execution. On its beta 1 version, Selenium Manager is invoked transparently by th
```suggestion
    "description": "Selenium Manager is a command-line tool developed in Rust to allow cross platform execution.",
```

2023-03-08 19:56 UTC, rashil2000 commented on bucket/selenium-manager.json
> +    "notes": "Check selenium-manager --help for usages, example : selenium-manager --browser chrome",
```suggestion
```
This is not required

2023-03-16 07:03 UTC, rashil2000 commented
/verify

2023-03-16 07:08 UTC, rashil2000 commented
/verify

2023-03-16 07:11 UTC, Baneeishaque commented
I appreciated your changes. I was little busy - that's why i can't respond in time.
Anyway, thank you for your corrections & commits.

Just because of curiosity, How do you find that binary is 64-bit only

2023-03-16 07:14 UTC, rashil2000 commented
> Just because of curiosity, How do you find that binary is 64-bit only?

Using a program called `file`: https://www.darwinsys.com/file/

2023-03-16 07:14 UTC, merged