slang: Add version 0.26.0
ScoopInstaller/Main pull request #4604
Opened 2023-03-25 05:02 UTC by Locietta

Closes #4603 

Upstreamed from my personal bucket: https://github.com/Locietta/sniffer/blob/master/bucket/slang.json

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-03-25 05:02 UTC, Locietta commented
/verify

2023-03-25 11:14 UTC, niheaven requested changes

2023-03-25 11:14 UTC, niheaven commented on bucket/slang.json
> +    "description": "Slang is a new language and compiler for shader development. It is designed to be a modern, extensible, and portable alternative to existing shading languages like HLSL and GLSL."
```suggestion
    "description": "A new language and compiler for shader development.",
```

2023-03-25 11:14 UTC, niheaven commented on bucket/slang.json
> +    "bin": "",
```suggestion
```

These are not needed.

2023-03-25 11:25 UTC, niheaven approved these changes

2023-03-29 21:28 UTC, rashil2000 commented
Is adding to Path really required? We could just make shims for `slangc.exe` and `slangd.exe` using the bin field.

2023-03-30 10:43 UTC, merged