Add support for *_HOME variables in rustup.
ScoopInstaller/Main pull request #5015
Opened 2023-08-10 09:35 UTC by marknefedov

Only set CARGO_HOME and RUSTUP_HOME environment variables if not set already.
If vars are set, install to those location.

Closes #5013 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-08-10 09:35 UTC, marknefedov commented
/verify

2023-08-11 12:38 UTC, rashil2000 commented
Hi @marknefedov!

Why did you close?

2023-08-11 12:41 UTC, marknefedov commented
In the issue it have been suggested to move to a separate manifest, and
apparently the last command in the post install script is unreliable, or it
is my windows installation being finicky. Feel free to use as a base though.

On Fri, 11 Aug 2023, 15:38 Rashil Gandhi, ***@***.***> wrote:

> Hi @marknefedov <https://github.com/marknefedov>!
>
> Why did you close?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ScoopInstaller/Main/pull/5015#issuecomment-1674706332>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEYTEC3VYTQEJEP4FLCWWWLXUYRV3ANCNFSM6AAAAAA3LG5ZTE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-12-01 13:33 UTC, brian6932 requested changes

2023-12-01 13:33 UTC, brian6932 commented on bucket/rustup.json
> +            "setx PATH \"%PATH%;%CARGO_HOME%\\bin\""
```suggestion
            "setx PATH \"$env:PATH;$env:CARGO_HOME\\bin\""
```
This is PowerShell not cmd, prob why it seemed "unreliable", wrong syntax

2024-01-13 22:03 UTC, HUMORCE commented
I keep my opinion that Scoop should manage the environment variables of Apps as possible. If other maintainers would like to merge it, feel free to go.

2024-06-21 19:27 UTC, closed without merging