Add Kyverno CLI manifest
ScoopInstaller/Main pull request #5115
Opened 2023-09-19 07:11 UTC by dhananjaysharma2004

I have created a manifest file for Kyverno CLI in the Scoop "Main" bucket which includes version info and download link for the Kyverno CLI and follows Scoop's manifest structure.

Relates to _https://github.com/kyverno/kyverno/issues/4322_

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-09-19 12:33 UTC, aliesbelik commented
Hi @dhananjaysharma2004.
Thank you for PR.

Could you please all the required points in [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md) first ([For Scoop buckets](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md#for-scoop-buckets)) and fix proposed manifest accordingly?

As well you can look for existent `kyverno-cli` manifests in other buckets, e.g.
https://github.com/hoilc/scoop-lemon/blob/master/bucket/kyverno-cli.json
https://github.com/okibcn/ScoopMaster/blob/master/bucket/kyverno-cli.json

2023-09-19 14:02 UTC, dhananjaysharma2004 commented
Hey @aliesbelik .                                                                                                                                                                                              I have checked all the required points in [contributing guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md) and proposed manifests and according to the existent `kyverno-cli` manifests in other buckets, I have made changes. Kindly check it, looking for your feedback, thanks!

2023-09-19 16:20 UTC, aliesbelik requested changes
Please fix `version` and remove trailing whitespaces across the manifest.
You can use automatic checks executed for manifest file to detect possible issues.

2023-09-19 16:20 UTC, aliesbelik commented on bucket/kyverno-cli.json
> +{
```suggestion
{
```

Unnecessary whitespaces.

2023-09-19 16:20 UTC, aliesbelik commented on bucket/kyverno-cli.json
> +    },
```suggestion
    },
```

Unnecessary whitespaces.

2023-09-19 16:20 UTC, aliesbelik commented on bucket/kyverno-cli.json
> +            "hash": "bcc11df1a17377357705d28e84be0f660fc9c43cae30a4440ade0aec5ee298be"
```suggestion
            "hash": "bcc11df1a17377357705d28e84be0f660fc9c43cae30a4440ade0aec5ee298be"
```

Unnecessary whitespaces.

2023-09-19 16:20 UTC, aliesbelik commented on bucket/kyverno-cli.json
> +    "bin": "kyverno.exe",
```suggestion
    "bin": "kyverno.exe",
```

Unnecessary whitespaces.

2023-09-19 16:20 UTC, aliesbelik commented on bucket/kyverno-cli.json
> +    "description": "The Kyverno Command Line Interface (CLI) is designed to validate and test policy behavior to resources prior to adding them to a cluster.",
```suggestion
    "description": "Kyverno CLI to manage Kubernetes policies", 
```

2023-09-19 16:20 UTC, aliesbelik commented on bucket/kyverno-cli.json
> +    "notes": "Kyverno CLI for managing Kubernetes policies.",
```suggestion
```

Duplicates description.

2023-09-19 17:13 UTC, dhananjaysharma2004 commented
Hey @aliesbelik , thanks for your guidance. Could you please guide me in solving the following issues also 

> Error: [-] files do not contain leading UTF-8 BOM

> Error: [-] files have no lines containing trailing whitespace     

 I added trailing whitespaces in my commit [d18d49a](https://github.com/ScoopInstaller/Main/pull/5115/commits/d18d49a2ead63dd107006e32c234c951a2b3920d) but it gave another error so I removed it in  [a14a0ed](https://github.com/ScoopInstaller/Main/pull/5115/commits/a14a0edfd0e4dad9811aa20aa39bad9daeb3bddf). Kindly guide me through this, looking for your feedback, thanks!

2023-09-19 18:19 UTC, rashil2000 commented
Please do not modify the settings file

2023-09-19 18:29 UTC, dhananjaysharma2004 commented
> Please do not modify the settings file

Hey @rashil2000 , I have maintained the settings file like it was before but could you tell me another alternative to insert UTF-8 BOM character at the begining of `kyverno-cli.json `

2023-09-20 16:38 UTC, aliesbelik commented
> Hey @rashil2000 , I have maintained the settings file like it was before but could you tell me another alternative to insert UTF-8 BOM character at the begining of `kyverno-cli.json `

Why do you want to submit UTF with BOM, if the linter's error message clearly points that is an issue?

> Error: [-] files do not contain leading UTF-8 BOM 1.59s (1.58s|9ms)
> Message
>   RuntimeException: The following files have utf-8 BOM: 
>   D:\a\Main\Main\my_bucket\bucket\kyverno-cli.json

Check your encoding settings, ensure that your editor doesn't insert leading BOM or remove it before commit in preferred manner.

2023-09-20 16:38 UTC, aliesbelik requested changes

2023-09-20 16:38 UTC, aliesbelik commented on bucket/kyverno-cli.json
> +    "bin": "kyverno.exe",
```suggestion
    "bin": "kyverno.exe",
```
I guess you could double check first before requesting review with the same error.

2023-09-20 17:46 UTC, dhananjaysharma2004 commented
@aliesbelik All checks have passed!

2023-09-20 18:16 UTC, aliesbelik commented
/verify

2023-09-22 11:57 UTC, aliesbelik approved these changes

2023-09-22 13:28 UTC, eddycharly commented
Thanks for that @dhananjaysharma2004 and @aliesbelik 

Quick question, do we need to open a new PR for every release or is there some kind of automation we can use for that ?

2023-09-22 13:47 UTC, dhananjaysharma2004 commented
The process of releasing new versions involves updating this manifest file with information about the new release, such as the version number, download links, and hash values. So, I think we need to open a new PR for every release. @aliesbelik kindly tell if there's some kind of automation for that.

2023-09-22 16:26 UTC, aliesbelik commented
> So, I think we need to open a new PR for every release.

No, (normally) you don't: [App Manifest Autoupdate](https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#testing-and-running-autoupdate).
Manifests in the bucket are updated reqularly via github action runs, using info from `autoupdate` section in the manifests themselves (if they have this section).
Another PR with updates will be required if, e.g., archives/binaries names or version/release notation will be changed, and autoupdate template becomes inactual.

2023-09-22 17:22 UTC, dhananjaysharma2004 commented
Ok I have used `autoupdate` section in this manifest so it is already automated.

2023-09-22 17:26 UTC, eddycharly commented
Awesome !

Thanks again @dhananjaysharma2004 and @aliesbelik

2023-09-22 17:42 UTC, dhananjaysharma2004 commented
> Awesome !
> 
> Thanks again @dhananjaysharma2004 and @aliesbelik

Your welcome @eddycharly ! I think now we can close [#4322](https://github.com/kyverno/kyverno/issues/4322)

2023-09-22 18:15 UTC, dhananjaysharma2004 commented
Thanks @aliesbelik ! Kindly merge this PR so we can close [#4322](https://github.com/kyverno/kyverno/issues/4322)

2023-09-27 08:06 UTC, eddycharly commented
@aliesbelik what are the next steps to get this in ?

2023-09-27 14:58 UTC, aliesbelik commented
@eddycharly I'm not a maintainer of this repo but only occasional contributor.
As for me your manifest looks good at the moment.
The only thing you could enhance is changing title of PR [as per Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md#for-scoop-buckets).
If there is any urgency with merging PR please contact maintainers.

2023-09-27 15:28 UTC, eddycharly commented
Nothing urgent, I just wanted to make sure we didn't miss anything expected, thanks !

2023-09-28 07:14 UTC, merged