unrar: Update to version 7.00, fix autoupdate link
ScoopInstaller/Main pull request #5277
Opened 2023-11-17 01:00 UTC by aliesbelik

- Update to version 7.00 (**7.00 beta 1**).
- Fix `autoupdate` link since no [unrarw32.exe](https://www.rarlab.com/rar/unrarw32.exe) is available but only [unrarw64.exe](https://www.rarlab.com/rar/unrarw64.exe) instead.
- Change `checkver` regex to track the latest/newest available version (including beta) since the only downloadable binary for unrar - [unrarw64.exe](https://www.rarlab.com/rar/unrarw64.exe) - reports its version as **7.00 beta 1** (i.e. latest) but not **6.24** (i.e. previous stable). Looks like there is no possibility to define what version has the downloadable binary: link is always the same - https://www.rarlab.com/rar/unrarw64.exe - and doesn't content version as well.

Closes #5272

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-11-17 01:04 UTC, aliesbelik commented
/verify

2024-01-13 21:39 UTC, HUMORCE approved these changes

2024-01-13 21:48 UTC, HUMORCE commented
Alternative: Extract unrar from WinRAR then upload to https://github.com/ScoopInstaller/Binary

2024-01-13 22:06 UTC, HUMORCE requested changes
```
Error: String '7.00 beta 3' does not match regex pattern '^[\w\.\-+_]+$'.
```

Fill spaces with hyphen

2024-01-14 10:23 UTC, HUMORCE commented
https://github.com/ScoopInstaller/Binary/pull/22

2024-01-14 11:16 UTC, aliesbelik reviewed
Thank you for correction.

2024-01-14 18:38 UTC, HUMORCE commented
> Guess it may be a bit "cheating" and not sure if my solution is optimal, so feel free to correct.

You could just use the `replace` function in `checkver`, which would be easier.

---

We don't need to make changes for this manifest until https://github.com/ScoopInstaller/Binary/pull/22 is merged

2024-01-15 15:04 UTC, aliesbelik commented
> You could just use the `replace` function in `checkver`, which would be easier.

The first idea was to use 

    "checkver": {
        "regex": "RAR ([\\d.]+)\\s*([\\w]*)\\s*([\\d.]*) version",
        "replace": "${1}-${2}-${3}"
    },

but this will produce unnecessary hyphens when release becomes stable (i.e. `7.00` and so on instead of current `7.00 beta X`).
So the variant with script seems more universal since works in both the cases.

2024-01-17 15:00 UTC, HUMORCE approved these changes

2024-01-17 15:02 UTC, merged