fix: kustomize has changed to .zip from .tar.gz
ScoopInstaller/Main pull request #5346
Opened 2023-12-12 11:42 UTC by mikaello

Closes https://github.com/ScoopInstaller/Main/issues/5345

- [ ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-12-13 00:42 UTC, aliesbelik commented
/verify

2023-12-15 10:26 UTC, HUMORCE approved these changes

2023-12-15 10:28 UTC, HUMORCE requested changes
Fix checkver and update to latest, consider add arm64

2023-12-19 09:22 UTC, mikaello commented
> Fix checkver and update to latest, consider add arm64

What is wrong with `checkver`? 

Wouldn't the excavator update to latest given the correct `url`?

2023-12-22 15:31 UTC, HUMORCE commented
/verify

2023-12-22 15:33 UTC, HUMORCE commented
> What is wrong with checkver?

I'm not sure, but I updated it to make sure it would at least pass checks. Thank you.

2023-12-22 15:33 UTC, HUMORCE approved these changes

2023-12-22 15:33 UTC, merged

2023-12-22 19:11 UTC, mikaello commented
Thanks for fixing and merging, @HUMORCE