ssh3: Add version 0.1.4-bsd
ScoopInstaller/Main pull request #5365
Opened 2023-12-19 04:18 UTC by brian6932

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-12-19 04:18 UTC, brian6932 commented
/verify

2024-01-13 21:12 UTC, HUMORCE approved these changes

2024-01-13 21:17 UTC, HUMORCE requested changes
Current checkver will matching RC version, and what is different between `0.1.4` and `0.1.4-bsd`, its log is not clear.

2024-01-13 21:27 UTC, brian6932 commented
@HUMORCE `bsd` has server support for openbsd, I should update the branch anyway, it's a bit stale

2024-01-13 21:37 UTC, HUMORCE commented
Server support for BSD is not available before 0.1.4-bsd/0.1.4-rc2, so we should allow the manifest to use RC version for now. Once an stable version released, update the checkver as soon

2024-01-13 21:37 UTC, HUMORCE approved these changes

2024-01-13 21:37 UTC, merged