go-sqlcmd: Add version 1.5.0
ScoopInstaller/Main pull request #5384
Opened 2023-12-29 17:02 UTC by FilipDeVos

This PR will add the sqlcmd standalone implementation. sqlcmd is the standard Microsoft command line experience for Microsoft SQL Server and Azure SQL

Closes #5367

- [ X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2023-12-29 17:17 UTC, FilipDeVos commented
/verify

2023-12-29 17:47 UTC, FilipDeVos commented
/verify

2024-01-02 02:04 UTC, aliesbelik requested changes
Guess it wouldn't be superfluous to add arm64 version as well.

2024-01-02 02:04 UTC, aliesbelik commented on bucket/go-sqlcmd.json
> +        }
```suggestion
        },
        "arm64": {
            "url": "https://github.com/microsoft/go-sqlcmd/releases/download/v1.5.0/sqlcmd-v1.5.0-windows-arm64.zip",
            "hash": "28ae735730f0020a0d44c9e453f56979c2da2a5e313e2f1209d3fbb121c361a1"
        }
```

2024-01-02 02:04 UTC, aliesbelik commented on bucket/go-sqlcmd.json
> +            }
```suggestion
            },
            "arm64": {
                "url": "https://github.com/microsoft/go-sqlcmd/releases/download/v$version/sqlcmd-v$version-windows-arm64.zip"
            }
```

2024-01-05 17:42 UTC, FilipDeVos commented on bucket/go-sqlcmd.json
> +            }
Added arm64 support

2024-01-05 17:43 UTC, FilipDeVos commented
/verify

2024-01-10 15:43 UTC, HUMORCE approved these changes

2024-01-10 15:44 UTC, merged