radius: Add version 0.29.0
ScoopInstaller/Main pull request #5477
Opened 2024-01-29 16:41 UTC by craigktreasure

This change adds the [radius](https://github.com/radius-project/radius) CLI tool to the bucket.

Closes #5474

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

As pointed out in the issue, there is another instance of this manifest for comparison [here](https://github.com/hoilc/scoop-lemon/blob/master/bucket/radius.json).

2024-01-29 16:41 UTC, craigktreasure commented
/verify

2024-02-03 04:34 UTC, craigktreasure commented
/verify

2024-03-06 23:26 UTC, tech189 requested changes
Looks good otherwise!

2024-03-07 03:15 UTC, craigktreasure commented
/verify

2024-03-07 03:16 UTC, craigktreasure commented on bucket/radius.json
> +    "checkver": {
Thanks @tech189! Accepted the change.

2024-03-07 06:49 UTC, craigktreasure commented
/verify

2024-03-07 13:32 UTC, merged

2024-03-07 13:32 UTC, tech189 commented
LGTM, thanks for your contribution!