Add timoni kubernetes package manager
ScoopInstaller/Main pull request #5493
Opened 2024-02-03 21:48 UTC by fcbry

Closes #5492
First contribution, so be gentle, I wasn't 100% certain how to deal with checksums/git versioning, so I used the existing cue.json to get started. Let me know what you think. 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2024-02-04 00:29 UTC, aliesbelik requested changes
Please try locally first with proposed changes.
Optionally you could use tools from [bin](https://github.com/ScoopInstaller/Main/tree/master/bin) to format and validate manifest.

2024-02-04 00:29 UTC, aliesbelik commented on bucket/timoni.json
> +  "version": "3.14.0",
```suggestion
  "version": "0.19.0",
```

Actual version.

2024-02-04 00:29 UTC, aliesbelik commented on bucket/timoni.json
> +      "extract_dir": "windows-amd64"
```suggestion
      "hash": "ab037ecc679fcbdfcf62203752182480d6a09a13a7560081bd9bce181bd5664d"
```

2024-02-04 00:29 UTC, aliesbelik commented on bucket/timoni.json
> +    "url": "https://github.com/stefanprodan/timoni/releases"
```suggestion
    "github": "https://github.com/stefanprodan/timoni"
```

2024-02-04 00:29 UTC, aliesbelik commented on bucket/timoni.json
> +        "url": "https://github.com/stefanprodan/timoni/releases/"
```suggestion
        "url": "https://github.com/stefanprodan/timoni/releases/download/v$version/timoni_$version_windows_amd64.zip"
```

2024-02-04 00:29 UTC, aliesbelik commented on bucket/timoni.json
> +      "url": "$baseurl/timoni_${version}_checksums.txt"
```suggestion
      "url": "$baseurl/timoni_$version_checksums.txt"
```

2024-02-05 12:37 UTC, aliesbelik commented
/verify

2024-02-05 12:40 UTC, aliesbelik approved these changes
Looks good to me.

2024-02-28 16:49 UTC, tech189 approved these changes

2024-02-28 16:50 UTC, tech189 commented
Thank you both!

2024-02-28 16:50 UTC, merged