fastfetch: update binary URL
ScoopInstaller/Main pull request #5504
Opened 2024-02-10 10:49 UTC by CarterLi

Update the file name pattern of fastfetch to match the latest version.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2024-02-10 15:32 UTC, aliesbelik requested changes

2024-02-10 15:32 UTC, aliesbelik commented on bucket/fastfetch.json
> +                "url": "https://github.com/fastfetch-cli/fastfetch/releases/download/$version/fastfetch-$version-windows-i6i6.7z"
```suggestion
                "url": "https://github.com/fastfetch-cli/fastfetch/releases/download/$version/fastfetch-$version-windows-i686.7z"
```

2024-02-10 16:01 UTC, CarterLi commented
oops

2024-02-10 18:48 UTC, aliesbelik commented
/verify

2024-02-23 08:30 UTC, CarterLi commented
Any chance to merge it?

2024-02-23 09:08 UTC, merged