px: fix px.ini creation for persist directive
ScoopInstaller/Main pull request #5610
Opened 2024-03-14 14:38 UTC by nicerloop

Initialize px.ini before persist directive to avoid creating a px.ini folder.
Configure PX_CONFIG environment variable to point to persist/px/px.ini.
 
Closes https://github.com/ScoopInstaller/Main/issues/5609

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2024-03-14 15:15 UTC, Ok-University2412 requested changes
来自黑客授权的代码，请求撤回

2024-03-14 23:30 UTC, Ok-University2412 requested changes
黑客使用代码以及开发软件进行违规攻击

2024-03-15 15:10 UTC, tech189 requested changes

2024-04-17 14:07 UTC, tech189 commented
Merging now so that more px.ini folders are not created 😅

2024-04-17 14:08 UTC, merged