granted: Add version 0.21.0 (#5650)
ScoopInstaller/Main pull request #5651
Opened 2024-03-26 10:42 UTC by aviv-julienjehannet

Closes #5650

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2024-03-28 23:35 UTC, aliesbelik commented
/verify

2024-03-28 23:58 UTC, aliesbelik requested changes
- Fix autoupdate link.
- Add arm64 version.

2024-03-28 23:58 UTC, aliesbelik commented on bucket/granted.json
> +                "url": "https://releases.commonfate.io/granted/v$version/granted_$version_windows_amd64.zip"
```suggestion
                "url": "https://releases.commonfate.io/granted/v$version/granted_$version_windows_x86_64.zip"
```

Fix autoupdate.

2024-03-28 23:58 UTC, aliesbelik commented on bucket/granted.json
> +        }
```suggestion
        },
        "arm64": {
            "url": "https://releases.commonfate.io/granted/v0.21.1/granted_0.21.1_windows_arm64.zip",
            "hash": "b0078405f26d6eecfa49efc102eb2271da1d56682e89190cd89c72dc32f55f2f"
        }
```

2024-03-28 23:58 UTC, aliesbelik commented on bucket/granted.json
> +            }
```suggestion
            },
            "arm64": {
                "url": "https://releases.commonfate.io/granted/v$version/granted_$version_windows_arm64.zip"
            }
```

Add arm64 version as well.

2024-03-28 23:58 UTC, aliesbelik commented on bucket/granted.json
> +    "depends": ["aws"],
```suggestion
    "depends": "aws",
```

2024-03-29 23:31 UTC, aviv-julienjehannet commented
Sorry for the low quality of the initial pull-request.
Thank you so much @aliesbelik for your suggestions.

2024-03-30 01:27 UTC, aliesbelik commented
/verify

2024-04-18 15:01 UTC, tech189 reviewed
Looks all good to me, only issue is I can't update to v0.23.0 because the arm64 download is not working at the moment.

2024-04-25 12:39 UTC, aviv-julienjehannet commented
Some news: Common Fate use GoReleaser to publish the builds and they have to upgrade GoReleaser and rerun the release pipeline. They will report back next week for an update.
In doing that, I'll be upgrading to last 0.23.2 version

2024-04-30 10:31 UTC, aviv-julienjehannet commented
@tech189 Chris Norman (from Common Fate) confirms the build fix. All should be ok now.

2024-04-30 11:45 UTC, aviv-julienjehannet commented
/verify

2024-04-30 14:01 UTC, tech189 approved these changes

2024-04-30 14:04 UTC, merged