Add pocketbase@0.22.9
ScoopInstaller/Main pull request #5749
Opened 2024-04-24 16:47 UTC by simonsan

Closes #5748

- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

## Question to maintainers

They use a https://github.com/pocketbase/pocketbase/releases/download/v0.22.9/checksums.txt for their release. How would I do the auto-updating of the hashes? Is it enough to link to that URL in `hash.url`?

2024-04-26 11:06 UTC, aliesbelik requested changes
1. Add `autoupdate.hash` section.
2. Please add `arm64` version as well.

2024-04-26 11:06 UTC, aliesbelik commented on bucket/pocketbase.json
> +        }
```suggestion
        },
        "hash": {
            "url": "$baseurl/checksums.txt"
        }

```

2024-04-26 11:14 UTC, aliesbelik commented
As from [documentation](https://pocketbase.io/docs):

> The prebuilt PocketBase executable will automatically create and manage 2 new directories alongside the executable:
    - pb_data - stores your application data, uploaded files, etc. (usually should be added in .gitignore).
    - pb_migrations - contains JS migration files with your collection changes (can be safely committed in your repository).

Wonder if at least `pb_data` is worth to be [persistent](https://github.com/ScoopInstaller/Scoop/wiki/Persistent-data) - to store between updates.

2024-04-26 12:42 UTC, simonsan commented
> As from [documentation](https://pocketbase.io/docs):
> 
> > The prebuilt PocketBase executable will automatically create and manage 2 new directories alongside the executable:
> > - pb_data - stores your application data, uploaded files, etc. (usually should be added in .gitignore).
> > - pb_migrations - contains JS migration files with your collection changes (can be safely committed in your repository).
> 
> Wonder if at least `pb_data` is worth to be [persistent](https://github.com/ScoopInstaller/Scoop/wiki/Persistent-data) - to store between updates.

Yeah, probably both are worth to be persisted?

2024-04-26 12:51 UTC, simonsan commented
/verify

2024-05-03 14:12 UTC, simonsan commented
@aliesbelik Want to take another look, if this is enough?

2024-05-03 22:38 UTC, aliesbelik commented
Looks good to me.
But since i don't have write access in Main, please wait a bit more for merging.

2024-05-03 23:01 UTC, simonsan commented
> Looks good to me. But since i don't have write access in Main, please wait a bit more for merging.

Yes, I'm aware. Was really just to make sure, some future person merging finds a good to go PR. :) Thanks for looking over it. 👍🏽

2024-05-07 08:32 UTC, tech189 approved these changes

2024-05-07 08:33 UTC, merged