git-absorb
ScoopInstaller/Main pull request #6205
Opened 2024-09-21 21:58 UTC by daniel-liuzzi

Relates to #5602 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2024-09-24 01:48 UTC, HUMORCE requested changes
For 64bit programs, `architecture` is required.

2024-09-24 21:04 UTC, daniel-liuzzi commented
@HUMORCE according to the [App Manifest wiki][1], "if the app is not 32bit, architecture **can be** used to wrap the differences" so I understood it was optional, especially given there's only a single binary. In any case, I already added architecture.

[1]: https://github.com/ScoopInstaller/Scoop/wiki/App-Manifests#optional-properties

2024-09-25 02:16 UTC, HUMORCE commented
Yeah, but It's mandatory for all official buckets.

> If the application provides only a 32bit download, the architecture field is not required. In all other cases, architecture field is mandatory.
> 
> [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md)

2024-09-25 02:17 UTC, HUMORCE approved these changes

2024-09-25 11:59 UTC, merged