juliaup: Add version 1.17.4
ScoopInstaller/Main pull request #6210
Opened 2024-09-23 16:32 UTC by akielbowicz

Julia installer and version multiplexer. 

Closes #6209 

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2024-09-23 16:33 UTC, akielbowicz commented
/verify

2024-10-02 15:28 UTC, aliesbelik requested changes
- `checkver` required, otherwise autoupdate won't work.
- Please follow the standard order of fields in the json file, as per [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md#for-scoop-buckets).

2024-10-02 19:46 UTC, aliesbelik commented
/verify

2024-10-02 19:48 UTC, aliesbelik approved these changes

2024-11-07 04:15 UTC, chawyehsu approved these changes

2024-11-07 04:15 UTC, merged