f2: Update to v2.0.1
ScoopInstaller/Main pull request #6309
Opened 2024-11-07 07:04 UTC by ayoisaiah

- Update version to v2.0.1.
- Update homepage link to new docs website.

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2024-11-23 20:57 UTC, aliesbelik requested changes
If removed from `homepage`, github link should be explicitly pointed in `checkver`.

2024-11-23 20:57 UTC, aliesbelik commented on bucket/f2.json
>      "checkver": "github",
```suggestion
    "checkver": {
        "github": "https://github.com/ayoisaiah/f2"
    },
```

2024-11-24 10:16 UTC, aliesbelik commented
/verify

2024-11-24 10:18 UTC, aliesbelik approved these changes

2024-11-27 12:01 UTC, chawyehsu approved these changes

2024-11-27 12:01 UTC, merged