yamlfmt: Add version 0.14.0
ScoopInstaller/Main pull request #6346
Opened 2024-11-27 19:05 UTC by o-l-a-v

Closes #6345

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

2024-12-01 00:07 UTC, aliesbelik requested changes

2024-12-01 00:07 UTC, aliesbelik commented on bucket/yamlfmt.json
> +            "url": "https://github.com/google/yamlfmt/releases/download/v0.14.0/checksums.txt"
```suggestion
            "url": "$baseurl/checksums.txt"
```

2024-12-01 15:09 UTC, aliesbelik commented
/verify

2025-01-15 10:45 UTC, o-l-a-v commented
/verify

2025-01-15 11:58 UTC, stevehipwell approved these changes
LGTM

2025-01-15 11:59 UTC, merged